// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PE1.Webshop.Web.Data;

namespace PE1.Webshop.Web.Migrations
{
    [DbContext(typeof(WebShopDbContext))]
    [Migration("20240903103219_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PE1.Webshop.Core.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SmartPhone"
                        },
                        new
                        {
                            Id = 3L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TV"
                        },
                        new
                        {
                            Id = 4L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Games"
                        },
                        new
                        {
                            Id = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Large Electric"
                        });
                });

            modelBuilder.Entity("PE1.Webshop.Core.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CatergoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CatergoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Brand = "MSI",
                            CatergoryId = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "Gaming-laptop-GE63.gif",
                            Model = "GE63",
                            Name = "GAMING LAPTOP",
                            Price = 1549m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2L,
                            Brand = "ASUS",
                            CatergoryId = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "Gaming-laptop-GL504GM.jpg",
                            Model = "GL504GM",
                            Name = "GAMING LAPTOP",
                            Price = 1389m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 3L,
                            Brand = "MSI",
                            CatergoryId = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "MSI-Gaming-Laptop-GF63.png",
                            Model = "GF63",
                            Name = "GAMING LAPTOP",
                            Price = 995m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 4L,
                            Brand = "HP",
                            CatergoryId = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "HP-Gaming-Laptop-OMEN-15-ek1021nb-Intel-Core-i7.png",
                            Model = "OMEN 15-EK1021NB INTEL CORE I7-10870H",
                            Name = "GAMING LAPTOP",
                            Price = 2199m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 5L,
                            Brand = "HP",
                            CatergoryId = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "HP-Laptop-15-dw1050nb-Intel-Pentium.png",
                            Model = "15-DW1050NB INTEL PENTIUM GOLD 6405U (2B0C1EA)",
                            Name = "LAPTOP",
                            Price = 499m,
                            Rating = 2
                        },
                        new
                        {
                            Id = 6L,
                            Brand = "LENOVO",
                            CatergoryId = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "LENOVO-Laptop-Yoga-Slim-9-14ITL5-Intel-Core-i7.png",
                            Model = "YOGA SLIM 9 14ITL5 INTEL CORE I7-1065G7",
                            Name = "GAMING LAPTOP",
                            Price = 1999m,
                            Rating = 8
                        },
                        new
                        {
                            Id = 7L,
                            Brand = "LENVOVO",
                            CatergoryId = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "LENOVO-Laptop-IdeaPad-3.png",
                            Model = "15ALC6 AMD RYZEN 5 5500U (82KU00NLMB)",
                            Name = "LAPTOP IDEAPAD 3",
                            Price = 599m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 8L,
                            Brand = "SAMSUNG",
                            CatergoryId = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "S20.jpg",
                            Model = "S20",
                            Name = "GALAXY",
                            Price = 600m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 9L,
                            Brand = "SAMSUNG",
                            CatergoryId = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "S21.jpg",
                            Model = "S21",
                            Name = "GALAXY",
                            Price = 700m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 10L,
                            Brand = "SAMSUNG",
                            CatergoryId = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "S21-Ultra.jpg",
                            Model = "S21 ULTRA",
                            Name = "GALAXY",
                            Price = 1099m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 11L,
                            Brand = "APPLE",
                            CatergoryId = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "APPLE-iPhone-13-Pro-Max-5G-1-TB-Silver.png",
                            Model = "13 PRO MAX 5G 1 TB SILVER",
                            Name = "IPHONE",
                            Price = 1893m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 12L,
                            Brand = "APPLE",
                            CatergoryId = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "APPLE-iPhone-13-Pro-5G-1-TB.png",
                            Model = "13 PRO 5G 1 TB GRAPHITE",
                            Name = "IPHONE",
                            Price = 1795m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 13L,
                            Brand = "APPLE",
                            CatergoryId = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "APPLE-iPhone-SE-64-GB.png",
                            Model = "SE 64 GB 2ND GEN. ZWART (MX9R2ZD/A)",
                            Name = "IPHONE",
                            Price = 439m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 14L,
                            Brand = "SAMSUNG",
                            CatergoryId = 3L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "UE40T5300AWXXN.jpg",
                            Model = "UE40T5300AWXXN",
                            Name = "TV LED",
                            Price = 399m,
                            Rating = 3
                        },
                        new
                        {
                            Id = 15L,
                            Brand = "SAMSUNG",
                            CatergoryId = 3L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "QE65QN95AATXXN.jpg",
                            Model = "QE65QN95AATXXN",
                            Name = "TV NEO QLED 4K 65 INCH",
                            Price = 1389m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 16L,
                            Brand = "SAMSUNG",
                            CatergoryId = 3L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "43TU7020.png",
                            Model = "43TU7020",
                            Name = "CRYSTAL UHD",
                            Price = 439m,
                            Rating = 2
                        },
                        new
                        {
                            Id = 17L,
                            Brand = "SONY",
                            CatergoryId = 4L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "playstation3.jpg",
                            Model = "SLIM-320GB",
                            Name = "PLAYSTATION 3",
                            Price = 109m,
                            Rating = 1
                        },
                        new
                        {
                            Id = 18L,
                            Brand = "SONY",
                            CatergoryId = 4L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "Palystation4.png",
                            Model = "PRO-1TB",
                            Name = "PLAYSTATION 4",
                            Price = 250m,
                            Rating = 3
                        },
                        new
                        {
                            Id = 19L,
                            Brand = "SONY",
                            CatergoryId = 4L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "PlayStation5.png",
                            Model = "DIGITAL EDITION",
                            Name = "PLAYSTATION 5",
                            Price = 399m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 20L,
                            Brand = "BOSCH",
                            CatergoryId = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "BOSCH-Koel.png",
                            Model = "VRIESCOMBINATIE-E-(KGN39VLEA)",
                            Name = "KOELKAST",
                            Price = 599m,
                            Rating = 3
                        },
                        new
                        {
                            Id = 21L,
                            Brand = "LG",
                            CatergoryId = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "LG-Amerikaanse-koeling.png",
                            Model = "E-(GSXV90MCDE)",
                            Name = "AMERIKAANSE KOELKAST",
                            Price = 2599m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 22L,
                            Brand = "SAMSUNG",
                            CatergoryId = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "KoelingSamsung.jpg",
                            Model = "RS68A8831B1 SPACEMAX™",
                            Name = "AMERIKAANSE KOELKAST",
                            Price = 1298m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 23L,
                            Brand = "BOSCH",
                            CatergoryId = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "BOSCH-Wasmachine.png",
                            Model = "VOORLADER C (WAX32MM0FG)",
                            Name = "WASMACHINE",
                            Price = 989m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 24L,
                            Brand = "SAMSUNG",
                            CatergoryId = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "SAMSUNG-Wasmachine.png",
                            Model = "VOORLADER A (WW90T684ALE/S2)",
                            Name = "WASMACHINE",
                            Price = 749m,
                            Rating = 4
                        },
                        new
                        {
                            Id = 25L,
                            Brand = "LG",
                            CatergoryId = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "LG-Wasmachine.png",
                            Model = "VOORLADER E (LC1R7N2)",
                            Name = "WASMACHINE",
                            Price = 998m,
                            Rating = 5
                        },
                        new
                        {
                            Id = 26L,
                            Brand = "WHIRLPOOL",
                            CatergoryId = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "WHIRLPOOL-Wasmachine.png",
                            Model = "VOORLADER D (FFSBE 7438 WE F)",
                            Name = "WASMACHINE",
                            Price = 299m,
                            Rating = 1
                        },
                        new
                        {
                            Id = 27L,
                            Brand = "AEG",
                            CatergoryId = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageFileName = "AEG-Wasmachine.png",
                            Model = "VOORLADER PROSTEAM C (L7FE86PROS)",
                            Name = "WASMACHINE",
                            Price = 699m,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("PE1.Webshop.Core.Entities.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Desktop"
                        },
                        new
                        {
                            Id = 2L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Student"
                        },
                        new
                        {
                            Id = 3L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget"
                        },
                        new
                        {
                            Id = 4L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Speed"
                        },
                        new
                        {
                            Id = 5L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Family"
                        },
                        new
                        {
                            Id = 6L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 7L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Graphics card"
                        },
                        new
                        {
                            Id = 8L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = 9L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "kitchen"
                        },
                        new
                        {
                            Id = 10L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wash"
                        },
                        new
                        {
                            Id = 11L,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cooling"
                        });
                });

            modelBuilder.Entity("ProductProperty", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ProductProperty");

                    b.HasData(
                        new
                        {
                            ProductId = 1L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 1L,
                            PropertyId = 2L
                        },
                        new
                        {
                            ProductId = 1L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 1L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 1L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 1L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 1L,
                            PropertyId = 7L
                        },
                        new
                        {
                            ProductId = 1L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 2L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 2L,
                            PropertyId = 2L
                        },
                        new
                        {
                            ProductId = 2L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 2L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 2L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 2L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 2L,
                            PropertyId = 7L
                        },
                        new
                        {
                            ProductId = 2L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 3L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 3L,
                            PropertyId = 2L
                        },
                        new
                        {
                            ProductId = 3L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 3L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 3L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 3L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 3L,
                            PropertyId = 7L
                        },
                        new
                        {
                            ProductId = 4L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 4L,
                            PropertyId = 2L
                        },
                        new
                        {
                            ProductId = 4L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 4L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 4L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 4L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 4L,
                            PropertyId = 7L
                        },
                        new
                        {
                            ProductId = 4L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 5L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 5L,
                            PropertyId = 2L
                        },
                        new
                        {
                            ProductId = 5L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 5L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 5L,
                            PropertyId = 7L
                        },
                        new
                        {
                            ProductId = 6L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 6L,
                            PropertyId = 2L
                        },
                        new
                        {
                            ProductId = 6L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 6L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 6L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 6L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 6L,
                            PropertyId = 7L
                        },
                        new
                        {
                            ProductId = 6L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 7L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 7L,
                            PropertyId = 2L
                        },
                        new
                        {
                            ProductId = 7L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 7L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 7L,
                            PropertyId = 7L
                        },
                        new
                        {
                            ProductId = 8L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 8L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 8L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 9L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 9L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 9L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 10L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 10L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 10L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 10L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 11L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 11L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 11L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 11L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 12L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 12L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 12L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 12L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 13L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 13L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 13L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 14L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 14L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 14L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 14L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 14L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 15L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 15L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 15L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 15L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 15L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 16L,
                            PropertyId = 1L
                        },
                        new
                        {
                            ProductId = 16L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 16L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 16L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 17L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 17L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 17L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 18L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 18L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 18L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 19L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 19L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 19L,
                            PropertyId = 6L
                        },
                        new
                        {
                            ProductId = 19L,
                            PropertyId = 8L
                        },
                        new
                        {
                            ProductId = 20L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 20L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 20L,
                            PropertyId = 9L
                        },
                        new
                        {
                            ProductId = 20L,
                            PropertyId = 11L
                        },
                        new
                        {
                            ProductId = 21L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 21L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 21L,
                            PropertyId = 9L
                        },
                        new
                        {
                            ProductId = 21L,
                            PropertyId = 11L
                        },
                        new
                        {
                            ProductId = 22L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 22L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 22L,
                            PropertyId = 9L
                        },
                        new
                        {
                            ProductId = 22L,
                            PropertyId = 11L
                        },
                        new
                        {
                            ProductId = 23L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 23L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 23L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 23L,
                            PropertyId = 9L
                        },
                        new
                        {
                            ProductId = 23L,
                            PropertyId = 10L
                        },
                        new
                        {
                            ProductId = 24L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 24L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 24L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 24L,
                            PropertyId = 9L
                        },
                        new
                        {
                            ProductId = 24L,
                            PropertyId = 10L
                        },
                        new
                        {
                            ProductId = 25L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 25L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 25L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 25L,
                            PropertyId = 9L
                        },
                        new
                        {
                            ProductId = 25L,
                            PropertyId = 10L
                        },
                        new
                        {
                            ProductId = 26L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 26L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 26L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 26L,
                            PropertyId = 9L
                        },
                        new
                        {
                            ProductId = 26L,
                            PropertyId = 10L
                        },
                        new
                        {
                            ProductId = 27L,
                            PropertyId = 3L
                        },
                        new
                        {
                            ProductId = 27L,
                            PropertyId = 4L
                        },
                        new
                        {
                            ProductId = 27L,
                            PropertyId = 5L
                        },
                        new
                        {
                            ProductId = 27L,
                            PropertyId = 9L
                        },
                        new
                        {
                            ProductId = 27L,
                            PropertyId = 10L
                        });
                });

            modelBuilder.Entity("PE1.Webshop.Core.Entities.Product", b =>
                {
                    b.HasOne("PE1.Webshop.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CatergoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductProperty", b =>
                {
                    b.HasOne("PE1.Webshop.Core.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PE1.Webshop.Core.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PE1.Webshop.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
